---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://dep.nodesource.com/setup_13.x | sudo -E bash -

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["node.js"]
    state: latest
    update_cashe: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
